controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_register:
    path: '/register/{id}'
    controller: 'App\Controller\RegistrationController::register'